name: Test-Tutorials

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          # In case of version change, update README.md accordingly
          node-version: 16
      - run: |
          npm ci
          git config --global user.email "test@example.com"
          git config --global user.name "Test"
          npx ts-node scripts/tutorial-runner.ts docs/zkapps/tutorials/01-hello-world.mdx

  deploying-network:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    services:
      mina-local-network:
        image: o1labs/mina-local-network:rampup-latest-lightnet
        env:
          NETWORK_TYPE: 'single-node'
          PROOF_LEVEL: 'none'
        ports:
          - 3085:3085
          - 5432:5432
          - 8080:8080
          - 8181:8181
        # TODO: Disable logging for container as the workaround of long post-job-cleanup phase
        # - Will be fixed by improving logging as part of the work on:
        # - https://hub.docker.com/r/o1labs/mina-local-network
        options: --log-driver=none
    steps:
      - name: Wait for Mina Network readiness
        uses: o1-labs/wait-for-mina-network-action@v1
        with:
          mina-graphql-port: 8080
          max-attempts: 60
          polling-interval-ms: 10000
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run tutorial
        env:
          USE_LOCAL_NETWORK: 'true'
        continue-on-error: false
        run: |
          npm ci
          git config --global user.email "test@example.com"
          git config --global user.name "Test"
          pwd
          npx ts-node scripts/tutorial-runner.ts docs/zkapps/tutorials/01-hello-world.md
